### ISSUE TITLE
I run the code 5character,and I have some questions.

### ISSUE THREAD

**Issue by zzk2021** [Yanan-Wang-cs/ClonedPerson#6]

**Comment by zzk2021** [comment]
![image](https://user-images.githubusercontent.com/73774678/213915551-cf85e398-29aa-4774-9bfd-ee49e1ec1bcc.png)
I generate some characters. I have two questions.
1. the collar often abnormal. like the image.
2. I think this neural network your trained can't processing decorations very well, eg. bag. The bag's texture is seen as clothes's, which looks strange.
Looking forward for your reply.

**Comment by zzk2021** [comment]
![image](https://user-images.githubusercontent.com/73774678/213916586-b8c36d3c-72d0-467e-b0f9-1b6d76cd61eb.png)

Besides, the hands are the same. The texture looks so bad.

**Comment by ShengcaiLiao** [comment]
Hi, congratulations in getting the project successfully configured and run! Could you also show the original images used to generate these characters?

**Comment by zzk2021** [comment]
original images like this 
![image](https://user-images.githubusercontent.com/73774678/214530178-d5109e04-84d8-46b8-80c2-17047555f68f.png)
I get images from the network. Online pictures are usually not a standard pose, this model is wrong to generate hands and hair or other body part as cloth texture. 
If I do clothes segmentation, things will be better?

**Comment by zzk2021** [comment]
About collar problem I think it's cause of low collar.

**Comment by ShengcaiLiao** [comment]
Did you run the "person view qualification" step described in [Person view qualification by pose detection](https://github.com/Yanan-Wang-cs/ClonedPerson/tree/main/pipeline#person-view-qualification-by-pose-detection)? This step should be able to remove unqualified images, like the one you attached, with hands occluding clothes.

**Comment by ShengcaiLiao** [comment]
If you have some time, I would suggest you read Appendix B of the [paper](https://arxiv.org/pdf/2204.02611.pdf) for qualified image selection, especially Fig. C. We are not aiming at processing every image from the Internet, but just carefully select "good view" images with clothes best shown, since there is huge availability from web.

**Comment by ShengcaiLiao** [comment]
> If I do clothes segmentation, things will be better?

Segmentation could be considered, but besides segmentation, we still need to consider how to re-fill the occluded parts, otherwise there would be holes in the resulting character clothes. Again, instead of making these efforts, we would simply consider looking for more other images with good quality.

**Comment by zzk2021** [comment]
OK, I understand your intention. Thanks for your suggestion.
